---
title: "The League of Legends Professional Scene" #replace the title with something short and catchy to represent your project
subtitle: "Bret's Data Science Portfolio" #replace blank with your name
output:
  html_document:
    df_print: paged
---

## Abstract

[Here](https://www.youtube.com/watch?v=BGtROJeMPeE) is a link to a short video describing what league of legends is.

So far I have imported my data, cleaned it, added some
more continuous variables, and created some visuals to
analyze the data that I have created. My original data
set did not have enough continous variables so I worked
with the current variables to create some of my own that
I used to created my visuals for this deliverable.

### 1. Discovery and Data Preparation

In this first deliverable I imported the data, 
cleaned it up a bit, and created some continuous
variables with which to create some graphs for analysis.

[Here](deliverable1Link.nb.html) is more information about the dataset.

### 2. Model Planning and Building

The model that I want to focus on is what factors of a game
have the most impact on the win rate. The facctors that I am
looking at are the differences in xp, gold, cs, and KDA primarily.
These will be narrowed down as I run the model.

For an in depth look at these data comparisons
click [here](deliverable2.html)

### 3. Results and Operationalization

In [this](deliverable3.html) page you will find the model, and the 
analysis that I have done on the model.
I have talked about what the results mean, and why the solutions may
not always be the most optimal approach to ensuring a victory.

